# Is This Tweet Positive?

Bag of Words - https://en.wikipedia.org/wiki/Bag-of-words_model

**Credit:** http://ravikiranj.net/posts/2012/code/how-build-twitter-sentiment-analyzer/

In [1]:
from sklearn.feature_extraction.text import CountVectorizer

In [3]:
vectorizer = CountVectorizer(stop_words='english')

In [ ]:
vectorizer

In [4]:
X_train = [
    'Hey Cici sweetheart! Just wanted to let u know I luv u! OH! and will the mixtape drop soon? FANTASY RIDE MAY 5TH!!!!',
    'I heard about that contest! Congrats girl!!',
    'UNC!!! NCAA Champs!! Franklin St.: I WAS THERE!! WILD AND CRAZY!!!!!! Nothing like it...EVER http://tinyurl.com/49955t3',
    'Do you Share More #jokes #quotes #music #photos or #news #articles on #Facebook or #Twitter?',
    'Good night #Twitter and #TheLegionoftheFallen. 5:45am cimes awfully early!',
    'I just finished a 2.66 mi run with a pace of 11\'14"/mi with Nike+ GPS. #nikeplus #makeitcount',
    'Disappointing day. Attended a car boot sale to raise some funds for the sanctuary, made a total of 88p after the entry fee - sigh',
    'no more taking Irish car bombs with strange Australian women who can drink like rockstars...my head hurts.',
    'Just had some bloodwork done. My arm hurts'
]

y_train = [
    'positive',
    'positive',
    'positive',
    'neutral',
    'neutral',
    'neutral',
    'negative',
    'negative',
    'negative'
]

In [5]:
X_train = vectorizer.fit_transform(X_train)

In [6]:
vectorizer.get_feature_names()

['11',
 '14',
 '45am',
 '49955t3',
 '5th',
 '66',
 '88p',
 'arm',
 'articles',
 'attended',
 'australian',
 'awfully',
 'bloodwork',
 'bombs',
 'boot',
 'car',
 'champs',
 'cici',
 'cimes',
 'com',
 'congrats',
 'contest',
 'crazy',
 'day',
 'disappointing',
 'drink',
 'drop',
 'early',
 'entry',
 'facebook',
 'fantasy',
 'fee',
 'finished',
 'franklin',
 'funds',
 'girl',
 'good',
 'gps',
 'head',
 'heard',
 'hey',
 'http',
 'hurts',
 'irish',
 'jokes',
 'just',
 'know',
 'let',
 'like',
 'luv',
 'makeitcount',
 'mi',
 'mixtape',
 'music',
 'ncaa',
 'news',
 'night',
 'nike',
 'nikeplus',
 'oh',
 'pace',
 'photos',
 'quotes',
 'raise',
 'ride',
 'rockstars',
 'run',
 'sale',
 'sanctuary',
 'share',
 'sigh',
 'soon',
 'st',
 'strange',
 'sweetheart',
 'taking',
 'thelegionofthefallen',
 'tinyurl',
 'total',
 'twitter',
 'unc',
 'wanted',
 'wild',
 'women']

In [ ]:
[vectorizer.get_feature_names()[8], vectorizer.get_feature_names()[9], vectorizer.get_feature_names()[10]]

In [7]:
X_train

<9x84 sparse matrix of type '<class 'numpy.int64'>'
	with 90 stored elements in Compressed Sparse Row format>

In [ ]:
type(X_train)

In [8]:
X_train.toarray()

array([[0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0,
        0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0,
        0, 1, 1, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0,
        0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0,
        1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0,
        0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 

In [ ]:
vectorizer.inverse_transform(X_train)

In [ ]:
X_test = ['This woman is my sweetheart']
X_test = vectorizer.transform(X_test)
X_test.toarray()

## Predicting Sentiment from Tweet

In [9]:
X_test = ['Congrats @ravikiranj, i heard you wrote a new tech post on sentiment analysis']

In [10]:
X_test = vectorizer.transform(X_test)

In [11]:
X_test

<1x84 sparse matrix of type '<class 'numpy.int64'>'
	with 2 stored elements in Compressed Sparse Row format>

In [ ]:
[X_test.toarray()[0][8], X_test.toarray()[0][9], X_test.toarray()[0][10]]

In [12]:
X_test.toarray()

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])

In [ ]:
vectorizer.inverse_transform(X_test)

In [13]:
# import
from sklearn import naive_bayes

# instantiate
clf = naive_bayes.MultinomialNB()

# fit
clf.fit(X_train, y_train)

# predict
clf.predict(X_test)

array(['positive'], dtype='<U8')

Try another tweet!

In [15]:
X_test = ['I am very bored today.']
X_test = vectorizer.transform(X_test)

In [16]:
X_test.toarray()

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])

In [17]:
clf.predict(X_test)

array(['negative'], dtype='<U8')

In [18]:
X_test = ['Good morning!']
X_test = vectorizer.transform(X_test)
clf.predict(X_test)

array(['neutral'], dtype='<U8')

In [19]:
X_test = ['I luv you']
X_test = vectorizer.transform(X_test)
clf.predict(X_test)

array(['positive'], dtype='<U8')

In [20]:
import pickle

In [21]:
f = open('sentiment.pkl', 'wb')
pickle.dump(clf, f)
f.close()

In [24]:
!ls | grep sentiment

09-sentimental-analysis-on-tweets.ipynb
sentiment.pkl


In [25]:
f = open('sentiment.pkl', 'rb')
stored_sentiment = pickle.load(f)
f.close()

In [28]:
X_test = ['I luv you']
X_test = vectorizer.transform(X_test)
stored_sentiment.predict(X_test)

array(['positive'], dtype='<U8')

In [29]:
f = open('vectorizer.pkl', 'wb')
pickle.dump(vectorizer, f)
f.close()